#Requires -Version 5.1
# Build phone + watch APKs on JDK 17 and install via adb.
# Gradle 8.11 cannot run on Java 25+ from Android Studio JBR.
param(
    [string]$Watch = ""
)

# Do NOT use ErrorActionPreference Stop: java.exe -version and gradle write
# to stderr, and Windows PowerShell 5.1 treats that as NativeCommandError.
$ErrorActionPreference = "Continue"
if ($PSVersionTable.PSVersion.Major -ge 7) {
    $PSNativeCommandUseErrorActionPreference = $false
}
Set-Location $PSScriptRoot

function Get-JavaMajor([string]$javaExe) {
    if (-not (Test-Path $javaExe)) { return 0 }
    $quoted = '"' + $javaExe + '"'
    $ver = cmd.exe /c "$quoted -version 2>&1" | Out-String
    if ($ver -match 'version "1\.(\d+)') { return [int]$Matches[1] }
    if ($ver -match 'version "(\d+)') { return [int]$Matches[1] }
    return 0
}

function Find-Jdk17 {
    $dirs = New-Object System.Collections.Generic.List[string]
    $roots = @(
        "$env:ProgramFiles\Eclipse Adoptium",
        "$env:ProgramFiles\Microsoft",
        "$env:ProgramFiles\Java",
        "$env:ProgramFiles\Amazon Corretto",
        "$env:ProgramFiles\Zulu",
        "${env:ProgramFiles(x86)}\Eclipse Adoptium",
        "$env:LOCALAPPDATA\Programs\Eclipse Adoptium",
        "$env:USERPROFILE\.jdks",
        "$env:USERPROFILE\scoop\apps"
    )
    foreach ($root in $roots) {
        if (Test-Path $root) {
            Get-ChildItem $root -Directory -ErrorAction SilentlyContinue | ForEach-Object {
                [void]$dirs.Add($_.FullName)
                Get-ChildItem $_.FullName -Directory -ErrorAction SilentlyContinue | ForEach-Object {
                    [void]$dirs.Add($_.FullName)
                }
            }
        }
    }
    if ($env:JAVA_HOME) { [void]$dirs.Add($env:JAVA_HOME) }

    $javaCmd = Get-Command java -ErrorAction SilentlyContinue
    if ($javaCmd -and $javaCmd.Source) {
        $homeFromPath = Split-Path (Split-Path $javaCmd.Source -Parent) -Parent
        if ($homeFromPath) { [void]$dirs.Add($homeFromPath) }
    }

    foreach ($dir in $dirs) {
        $java = Join-Path $dir "bin\java.exe"
        if (-not (Test-Path $java)) { continue }
        $major = Get-JavaMajor $java
        if ($major -eq 17) { return $dir }
        if ($major -ge 25) {
            Write-Host "Skip Java $major ($dir) - Gradle 8.11 cannot run on it" -ForegroundColor DarkYellow
        }
    }
    return $null
}

function Find-AndroidSdk {
    $candidates = New-Object System.Collections.Generic.List[string]
    foreach ($item in @(
        $env:ANDROID_HOME,
        $env:ANDROID_SDK_ROOT,
        (Join-Path $env:LOCALAPPDATA "Android\Sdk"),
        (Join-Path $env:USERPROFILE "AppData\Local\Android\Sdk"),
        "C:\Users\Di\AppData\Local\Android\Sdk",
        "$env:ProgramFiles\Android\android-sdk",
        "${env:ProgramFiles(x86)}\Android\android-sdk"
    )) {
        if ($item) { [void]$candidates.Add($item) }
    }

    $localProps = Join-Path $PSScriptRoot "local.properties"
    if (Test-Path $localProps) {
        Get-Content $localProps | ForEach-Object {
            if ($_ -match '^\s*sdk\.dir\s*=\s*(.+)\s*$') {
                $fromFile = $Matches[1].Trim().Trim('"').Replace('/', '\')
                if ($fromFile) { [void]$candidates.Add($fromFile) }
            }
        }
    }

    foreach ($sdk in $candidates) {
        $adbPath = Join-Path $sdk "platform-tools\adb.exe"
        if (Test-Path $adbPath) {
            return [System.IO.Path]::GetFullPath($sdk)
        }
    }
    return $null
}

function Write-SdkLocalProperties([string]$sdk) {
    $file = Join-Path $PSScriptRoot "local.properties"
    $sdkUnix = $sdk.Replace('\', '/')
    $kept = @()
    if (Test-Path $file) {
        $kept = @(Get-Content $file | Where-Object { $_ -notmatch '^\s*sdk\.dir\s*=' })
    }
    $out = @()
    $out += "# Generated by build-install.cmd. Do not commit."
    foreach ($line in $kept) {
        if ($line -and ($line -notmatch '^\s*#')) { $out += $line }
    }
    $out += "sdk.dir=$sdkUnix"
    Set-Content -Path $file -Value $out -Encoding ASCII
}

Write-Host "==> Looking for JDK 17 (not Java 25/27 from Android Studio\jbr)..."
$jdk = Find-Jdk17
if (-not $jdk) {
    Write-Host "==> JDK 17 not found. Installing Eclipse Temurin 17 (winget)..."
    $winget = Get-Command winget -ErrorAction SilentlyContinue
    if (-not $winget) {
        Write-Host "winget not found. Install JDK 17: https://adoptium.net/temurin/releases/?version=17" -ForegroundColor Red
        Write-Host "Do not use Android Studio\jbr (Java 25/27). Gradle 8.11 needs JDK 17." -ForegroundColor Red
        exit 1
    }
    cmd.exe /c "winget install --id EclipseAdoptium.Temurin.17.JDK -e --accept-package-agreements --accept-source-agreements --disable-interactivity"
    $jdk = Find-Jdk17
}
if (-not $jdk) {
    Write-Host "JDK 17 still not found. Install https://adoptium.net/temurin/releases/?version=17" -ForegroundColor Red
    Write-Host "Then open a NEW window and run only: .\build-install.cmd" -ForegroundColor Red
    Write-Host "Do not set JAVA_HOME to Android Studio\jbr." -ForegroundColor Red
    exit 1
}

$env:JAVA_HOME = $jdk
$env:PATH = "$jdk\bin;" + $env:PATH
$major = Get-JavaMajor "$jdk\bin\java.exe"
if ($major -ne 17) {
    Write-Host "JAVA_HOME is still Java $major : $jdk" -ForegroundColor Red
    exit 1
}

Write-Host "==> JAVA_HOME=$env:JAVA_HOME"
cmd.exe /c "`"$jdk\bin\java.exe`" -version"

Write-Host "==> Looking for Android SDK..."
$sdk = Find-AndroidSdk
if (-not $sdk) {
    Write-Host "Android SDK not found (need platform-tools\adb.exe)." -ForegroundColor Red
    Write-Host "Android Studio: Settings -> Languages & Frameworks -> Android SDK -> Android SDK Location."
    Write-Host "Typical path: $env:LOCALAPPDATA\Android\Sdk"
    exit 1
}
Write-SdkLocalProperties $sdk
$env:ANDROID_HOME = $sdk
$env:ANDROID_SDK_ROOT = $sdk
$adb = Join-Path $sdk "platform-tools\adb.exe"
$env:PATH = "$(Join-Path $sdk 'platform-tools');" + $env:PATH
Write-Host "==> ANDROID_HOME=$sdk"
Write-Host "==> wrote sdk.dir in local.properties"

Write-Host "==> Building :app and :wear (Gradle 8.11 on JDK 17)..."
cmd.exe /c ".\gradlew.bat :app:assembleDebug :wear:assembleDebug --no-daemon"
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$phoneApk = "app\build\outputs\apk\debug\app-debug.apk"
$wearApk = "wear\build\outputs\apk\debug\wear-debug.apk"
if (-not (Test-Path $phoneApk) -or -not (Test-Path $wearApk)) {
    Write-Host "APK files were not produced." -ForegroundColor Red
    exit 1
}

Write-Host "==> adb: $adb"
cmd.exe /c "`"$adb`" start-server" | Out-Null
if ($Watch) {
    Write-Host "==> adb connect $Watch"
    cmd.exe /c "`"$adb`" connect $Watch"
}

$serials = @(cmd.exe /c "`"$adb`" devices") |
    Where-Object { $_ -match "\tdevice$" } |
    ForEach-Object { ($_ -split "\s+")[0] }

if ($serials.Count -eq 0) {
    Write-Host ""
    Write-Host "Build OK, but adb sees no devices." -ForegroundColor Yellow
    Write-Host "Phone: USB debugging, tap Allow this computer on the phone screen."
    Write-Host "Galaxy Watch Ultra (SM-L705F):"
    Write-Host "  Developer options -> Wireless debugging OFF, then ON."
    Write-Host "  The port changes every time. 192.168.2.142:36169 is already dead."
    Write-Host "  Copy IP:PORT from the watch and run:"
    Write-Host ""
    Write-Host "  .\build-install.cmd -Watch IP:PORT"
    Write-Host ""
    exit 2
}

$installed = $false
foreach ($serial in $serials) {
    if ($serial -match "^\d+\.\d+\.\d+\.\d+:") {
        Write-Host "==> Watch $serial <- wear APK (ru.sdvirk.healthsync.wear)"
        cmd.exe /c "`"$adb`" -s $serial install -r $wearApk"
        $installed = $true
    } else {
        Write-Host "==> Phone $serial <- app APK (ru.sdvirk.healthsync)"
        cmd.exe /c "`"$adb`" -s $serial install -r $phoneApk"
        $installed = $true
    }
}

if ($installed) {
    Write-Host "==> Done. Open Health Sync Watch on the watch, Health Sync on the phone."
}
