#Requires -Version 5.1
# Build phone + watch APKs on JDK 17 and install via adb.
# Gradle 8.11 cannot run on Java 25+ from Android Studio JBR.
param(
    [string]$Watch = "",
    [string]$Pair = "",
    [string]$PairCode = "",
    [switch]$Rebuild
)

# Do NOT use ErrorActionPreference Stop: java.exe -version and gradle write
# to stderr, and Windows PowerShell 5.1 treats that as NativeCommandError.
$ErrorActionPreference = "Continue"
if ($PSVersionTable.PSVersion.Major -ge 7) {
    $PSNativeCommandUseErrorActionPreference = $false
}
Set-Location $PSScriptRoot

function Get-JavaMajor([string]$javaExe) {
    if (-not (Test-Path $javaExe)) { return 0 }
    $quoted = '"' + $javaExe + '"'
    $ver = cmd.exe /c "$quoted -version 2>&1" | Out-String
    if ($ver -match 'version "1\.(\d+)') { return [int]$Matches[1] }
    if ($ver -match 'version "(\d+)') { return [int]$Matches[1] }
    return 0
}

function Find-Jdk17 {
    $dirs = New-Object System.Collections.Generic.List[string]
    $roots = @(
        "$env:ProgramFiles\Eclipse Adoptium",
        "$env:ProgramFiles\Microsoft",
        "$env:ProgramFiles\Java",
        "$env:ProgramFiles\Amazon Corretto",
        "$env:ProgramFiles\Zulu",
        "${env:ProgramFiles(x86)}\Eclipse Adoptium",
        "$env:LOCALAPPDATA\Programs\Eclipse Adoptium",
        "$env:USERPROFILE\.jdks",
        "$env:USERPROFILE\scoop\apps"
    )
    foreach ($root in $roots) {
        if (Test-Path $root) {
            Get-ChildItem $root -Directory -ErrorAction SilentlyContinue | ForEach-Object {
                [void]$dirs.Add($_.FullName)
                Get-ChildItem $_.FullName -Directory -ErrorAction SilentlyContinue | ForEach-Object {
                    [void]$dirs.Add($_.FullName)
                }
            }
        }
    }
    if ($env:JAVA_HOME) { [void]$dirs.Add($env:JAVA_HOME) }

    $javaCmd = Get-Command java -ErrorAction SilentlyContinue
    if ($javaCmd -and $javaCmd.Source) {
        $homeFromPath = Split-Path (Split-Path $javaCmd.Source -Parent) -Parent
        if ($homeFromPath) { [void]$dirs.Add($homeFromPath) }
    }

    foreach ($dir in $dirs) {
        $java = Join-Path $dir "bin\java.exe"
        if (-not (Test-Path $java)) { continue }
        $major = Get-JavaMajor $java
        if ($major -eq 17) { return $dir }
        if ($major -ge 25) {
            Write-Host "Skip Java $major ($dir) - Gradle 8.11 cannot run on it" -ForegroundColor DarkYellow
        }
    }
    return $null
}

function Find-AndroidSdk {
    $candidates = New-Object System.Collections.Generic.List[string]
    foreach ($item in @(
        $env:ANDROID_HOME,
        $env:ANDROID_SDK_ROOT,
        (Join-Path $env:LOCALAPPDATA "Android\Sdk"),
        (Join-Path $env:USERPROFILE "AppData\Local\Android\Sdk"),
        "C:\Users\Di\AppData\Local\Android\Sdk",
        "$env:ProgramFiles\Android\android-sdk",
        "${env:ProgramFiles(x86)}\Android\android-sdk"
    )) {
        if ($item) { [void]$candidates.Add($item) }
    }

    $localProps = Join-Path $PSScriptRoot "local.properties"
    if (Test-Path $localProps) {
        Get-Content $localProps | ForEach-Object {
            if ($_ -match '^\s*sdk\.dir\s*=\s*(.+)\s*$') {
                $fromFile = $Matches[1].Trim().Trim('"').Replace('/', '\')
                if ($fromFile) { [void]$candidates.Add($fromFile) }
            }
        }
    }

    foreach ($sdk in $candidates) {
        $adbPath = Join-Path $sdk "platform-tools\adb.exe"
        if (Test-Path $adbPath) {
            return [System.IO.Path]::GetFullPath($sdk)
        }
    }
    return $null
}

function Write-SdkLocalProperties([string]$sdk) {
    $file = Join-Path $PSScriptRoot "local.properties"
    $sdkUnix = $sdk.Replace('\', '/')
    $kept = @()
    if (Test-Path $file) {
        $kept = @(Get-Content $file | Where-Object { $_ -notmatch '^\s*sdk\.dir\s*=' })
    }
    $out = @()
    $out += "# Generated by build-install.cmd. Do not commit."
    foreach ($line in $kept) {
        if ($line -and ($line -notmatch '^\s*#')) { $out += $line }
    }
    $out += "sdk.dir=$sdkUnix"
    Set-Content -Path $file -Value $out -Encoding ASCII
}

function Resolve-WatchTarget([string]$raw) {
    if (-not $raw) { return $null }
    if ($raw -match '(\d{1,3}(?:\.\d{1,3}){3}:\d{1,5})') {
        $endpoint = $Matches[1]
        if ($raw -ne $endpoint) {
            Write-Host "Watch argument was '$raw' - using $endpoint" -ForegroundColor Yellow
            Write-Host "Do not type the word IP. Numbers only." -ForegroundColor Yellow
        }
        return $endpoint
    }
    Write-Host "Bad -Watch value: '$raw'" -ForegroundColor Red
    Write-Host "Copy ONLY the numbers from the watch, for example:" -ForegroundColor Red
    Write-Host "  .\build-install.cmd -Watch 192.168.2.142:38959" -ForegroundColor Red
    Write-Host "Not: -Watch IP:192.168.2.142:38959" -ForegroundColor Red
    exit 1
}

$watchTarget = Resolve-WatchTarget $Watch
$pairTarget = $null
if ($Pair) { $pairTarget = Resolve-WatchTarget $Pair }

$phoneApk = "app\build\outputs\apk\debug\app-debug.apk"
$wearApk = "wear\build\outputs\apk\debug\wear-debug.apk"
$haveApks = (Test-Path $phoneApk) -and (Test-Path $wearApk)
$needBuild = $Rebuild -or (-not $haveApks)

Write-Host "==> Looking for Android SDK..."
$sdk = Find-AndroidSdk
if (-not $sdk) {
    Write-Host "Android SDK not found (need platform-tools\adb.exe)." -ForegroundColor Red
    Write-Host "Android Studio: Settings -> Languages & Frameworks -> Android SDK -> Android SDK Location."
    Write-Host "Typical path: $env:LOCALAPPDATA\Android\Sdk"
    exit 1
}
Write-SdkLocalProperties $sdk
$env:ANDROID_HOME = $sdk
$env:ANDROID_SDK_ROOT = $sdk
$adb = Join-Path $sdk "platform-tools\adb.exe"
$env:PATH = "$(Join-Path $sdk 'platform-tools');" + $env:PATH
Write-Host "==> ANDROID_HOME=$sdk"

if ($needBuild) {
    Write-Host "==> Looking for JDK 17 (not Java 25/27 from Android Studio\jbr)..."
    $jdk = Find-Jdk17
    if (-not $jdk) {
        Write-Host "==> JDK 17 not found. Installing Eclipse Temurin 17 (winget)..."
        $winget = Get-Command winget -ErrorAction SilentlyContinue
        if (-not $winget) {
            Write-Host "winget not found. Install JDK 17: https://adoptium.net/temurin/releases/?version=17" -ForegroundColor Red
            Write-Host "Do not use Android Studio\jbr (Java 25/27). Gradle 8.11 needs JDK 17." -ForegroundColor Red
            exit 1
        }
        cmd.exe /c "winget install --id EclipseAdoptium.Temurin.17.JDK -e --accept-package-agreements --accept-source-agreements --disable-interactivity"
        $jdk = Find-Jdk17
    }
    if (-not $jdk) {
        Write-Host "JDK 17 still not found. Install https://adoptium.net/temurin/releases/?version=17" -ForegroundColor Red
        Write-Host "Then open a NEW window and run only: .\build-install.cmd" -ForegroundColor Red
        Write-Host "Do not set JAVA_HOME to Android Studio\jbr." -ForegroundColor Red
        exit 1
    }

    $env:JAVA_HOME = $jdk
    $env:PATH = "$jdk\bin;" + $env:PATH
    $major = Get-JavaMajor "$jdk\bin\java.exe"
    if ($major -ne 17) {
        Write-Host "JAVA_HOME is still Java $major : $jdk" -ForegroundColor Red
        exit 1
    }

    Write-Host "==> JAVA_HOME=$env:JAVA_HOME"
    cmd.exe /c "`"$jdk\bin\java.exe`" -version"

    Write-Host "==> Building :app and :wear (Gradle 8.11 on JDK 17)..."
    cmd.exe /c ".\gradlew.bat :app:assembleDebug :wear:assembleDebug --no-daemon"
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    if (-not (Test-Path $phoneApk) -or -not (Test-Path $wearApk)) {
        Write-Host "APK files were not produced." -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "==> APKs already exist, skipping Gradle (pass -Rebuild to force)"
}

Write-Host "==> adb: $adb"
& $adb kill-server | Out-Null
& $adb start-server | Out-Null

if ($pairTarget) {
    Write-Host "==> adb pair $pairTarget"
    Write-Host "Keep the pairing screen open on the watch (6-digit code)."
    if ($PairCode) {
        & $adb pair $pairTarget $PairCode
    } else {
        Write-Host "Type the 6-digit code from the watch, then Enter."
        & $adb pair $pairTarget
    }
}

if ($watchTarget) {
    Write-Host "==> adb connect $watchTarget"
    $connectOut = & $adb connect $watchTarget 2>&1 | ForEach-Object { "$_" }
    Write-Host ($connectOut -join " ")
}

$serials = @(& $adb devices) |
    Where-Object { $_ -match "\tdevice$" } |
    ForEach-Object { ($_ -split "\s+")[0] }

if ($serials.Count -eq 0) {
    $ipHint = "192.168.2.142"
    $connectHint = "36723"
    if ($watchTarget -and ($watchTarget -match '^([^:]+):(\d+)$')) {
        $ipHint = $Matches[1]
        $connectHint = $Matches[2]
    }
    Write-Host ""
    Write-Host "APKs are built, but adb did not connect." -ForegroundColor Yellow
    Write-Host "Galaxy Watch Ultra needs PAIRING first, then CONNECT. Two different ports."
    Write-Host "PC and watch must be on the same Wi-Fi (same 192.168.2.x)."
    Write-Host ""
    Write-Host "On the watch: Developer options -> Wireless debugging ON."
    Write-Host "  Main screen IP:port  = CONNECT  (you tried $ipHint`:$connectHint)"
    Write-Host "  Pair with pairing code = another port + 6-digit code. Leave that screen open."
    Write-Host ""
    Write-Host "Then:"
    Write-Host "  .\build-install.cmd -Pair $ipHint`:PAIR_PORT -PairCode 123456 -Watch $ipHint`:$connectHint"
    Write-Host ""
    Write-Host "Phone: USB cable + USB debugging, tap Allow this computer."
    Write-Host ""
    exit 2
}

$installed = $false
foreach ($serial in $serials) {
    if ($serial -match "^\d+\.\d+\.\d+\.\d+:") {
        Write-Host "==> Watch $serial <- wear APK (ru.sdvirk.healthsync.wear)"
        cmd.exe /c "`"$adb`" -s $serial install -r $wearApk"
        $installed = $true
    } else {
        Write-Host "==> Phone $serial <- app APK (ru.sdvirk.healthsync)"
        cmd.exe /c "`"$adb`" -s $serial install -r $phoneApk"
        $installed = $true
    }
}

if ($installed) {
    Write-Host "==> Done. Open Health Sync Watch on the watch, Health Sync on the phone."
}
